namespace TravelPal.Models
{
    public enum Country
    {
        Afghanistan,

        Algeria,
        Andorra,
        Angola,
        Antigua,
        Argentina,
        Armenia,
        Australia,

        Azerbaijan,
        Bahamas,
        Bahrain,
        Bangladesh,
        Barbados,
        Belarus,

        Belize,
        Benin,
        Bhutan,
        Bolivia,

        Botswana,
        Brazil,
        Brunei,

        Burundi,
        CaboVerde,
        Cambodia,
        Cameroon,
        Canada,
        Chad,
        Chile,
        China,
        Colombia,
        Comoros,
        Congo,

        Cuba,



        Djibouti,
        Dominica,
        DominicanRepublic,
        Ecuador,
        Egypt,
        ElSalvador,
        EquatorialGuinea,
        Eritrea,

        Eswatini,
        Ethiopia,
        Fiji,

        Gabon,
        Gambia,
        Georgia,

        Ghana,

        Grenada,
        Guatemala,
        Guinea,
        GuineaBissau,
        Guyana,
        Haiti,
        Honduras,

        India,
        Indonesia,
        Iran,
        Iraq,

        Israel,

        Jamaica,
        Japan,
        Jordan,
        Kazakhstan,
        Kenya,
        Kiribati,
        KoreaNorth,
        KoreaSouth,

        Kuwait,
        Kyrgyzstan,
        Laos,

        Lebanon,
        Lesotho,
        Liberia,
        Libya,



        Madagascar,
        Malawi,
        Malaysia,
        Maldives,
        Mali,

        MarshallIslands,
        Mauritania,
        Mauritius,
        Mexico,


        Mongolia,

        Morocco,
        Mozambique,
        Myanmar,
        Namibia,
        Nauru,
        Nepal,

        NewZealand,
        Nicaragua,
        Niger,
        Nigeria,


        Oman,
        Pakistan,
        Palau,
        Panama,
        PapuaNewGuinea,
        Paraguay,
        Peru,
        Philippines,

        Qatar,

        Rwanda,
        SaintLucia,
        Samoa,

        SaudiArabia,
        Senegal,

        Seychelles,
        SierraLeone,
        Singapore,

        SolomonIslands,
        Somalia,
        SouthAfrica,

        SriLanka,
        Sudan,
        SudanSouth,
        Suriname,


        Syria,
        Taiwan,
        Tajikistan,
        Tanzania,
        Thailand,
        Togo,
        Tonga,
        Trinidad,
        Tunisia,
        Turkey,
        Turkmenistan,
        Tuvalu,
        Uganda,

        UnitedStates,
        Uruguay,
        Uzbekistan,
        Vanuatu,

        Venezuela,
        Vietnam,
        Yemen,
        Zambia,
        Zimbabwe,

        Albania,
        Austria,
        Belgium,
        Bosnia,
        Bulgaria,

        Croatia,
        CzechRepublic,
        Cyprus,
        Denmark,
        Estonia,
        Finland,
        France,
        Germany,
        Greece,
        Hungary,
        Iceland,
        Ireland,
        Italy,
        Kosovo,
        Latvia,
        Liechtenstein,
        Lithuania,
        Luxembourg,
        Malta,
        Moldova,
        Monaco,
        Montenegro,
        Netherlands,
        NorthMacedonia,
        Norway,
        Poland,
        Portugal,
        Romania,
        Russia,
        SanMarino,
        Serbia,
        Slovakia,
        Slovenia,
        Spain,
        Sweden,
        Switzerland,
        Ukraine,
        UnitedKingdom,
        VaticanCity,

    }


    public enum EuropeanCountry
    {
        Albania,
        Austria,
        Belgium,
        Bosnia,
        Bulgaria,

        Croatia,
        CzechRepublic,
        Cyprus,
        Denmark,
        Estonia,
        Finland,
        France,
        Germany,
        Greece,
        Hungary,
        Iceland,
        Ireland,
        Italy,
        Kosovo,
        Latvia,
        Liechtenstein,
        Lithuania,
        Luxembourg,
        Malta,
        Moldova,
        Monaco,
        Montenegro,
        Netherlands,
        NorthMacedonia,
        Norway,
        Poland,
        Portugal,
        Romania,
        Russia,
        SanMarino,
        Serbia,
        Slovakia,
        Slovenia,
        Spain,
        Sweden,
        Switzerland,
        Ukraine,
        UnitedKingdom,
        VaticanCity,
    }
}
